name: calculator_app_test

on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v.1.3.0
      - name: install dependencies
        run: flutter packages get
      - name: run tests
        run: flutter test --exclude-tags='no-ci'